"""init

Revision ID: c96baf480013
Revises: 
Create Date: 2026-06-16 13:28:53.598335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96baf480013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('tipo_cliente', sa.String(length=20), nullable=False),
    sa.Column('valor_compra', sa.Float(), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=False),
    sa.Column('cashback', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultas')
    # ### end Alembic commands ###
